webpersonal/project/models.py
from webpersonal import db


class Project(db.Model):
    __tablename__ = 'projects'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.Text)

    def __init__(self, title, description):
        self.title = title
        self.description = description

    def __repr__(self):
        return f'Project: {self.title}'

# p1 = Project('Proyecto 01', 'Descripcion de proyecto 01')
# p2 = Project('Proyecto 02', 'Descripcion de proyecto 02')
# p3 = Project('Proyecto 03', 'Descripcion de proyecto 03')

# PROYECTS = [p1, p2, p3]

webpersonal/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Configuración de la App
app.config.from_object('config.DevelopmentConfig')
db = SQLAlchemy(app)

from webpersonal.views import base
from webpersonal.project.views import project

app.register_blueprint(base)
app.register_blueprint(project)
# import webpersonal.views

# Ejecutar todas las consultas
db.create_all()

webpersonal/project/views.py
from flask import render_template, Blueprint, request, url_for, redirect
# from webpersonal.project.models import PROYECTS
from webpersonal.project.models import Project
from webpersonal import db

project = Blueprint('project', __name__)


@project.route('/projects')
@project.route('/projects/index')
def index():
    projects = Project.query.all()
    db.session.commit()
    print(projects)
    return render_template('project/index.html', projects=projects)


@project.route('/projects/create')
def create():
    return render_template('project/create.html')


@project.route('/projects/insert', methods=['POST'])
def insert():
    title = request.form.get('title')
    description = request.form['description']
    project = Project(title, description)
    db.session.add(project)
    db.session.commit()
    return redirect(url_for('project.index'))


@project.route('/projects/edit/<int:id>')
def edit(id):
    project = Project.query.get_or_404(id)
    return render_template('project/edit.html', project=project)


@project.route('/projects/update/<int:id>', methods=['POST'])
def update(id):
    project = Project.query.get_or_404(id)
    project.title = request.form.get('title')
    project.description = request.form['description']
    db.session.add(project)
    db.session.commit()
    return redirect(url_for('project.index'))


@project.route('/projects/delete/<int:id>')
def delete(id):
    project = Project.query.get_or_404(id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('project.index'))

webpersonal/views.py
from flask import render_template, Blueprint

base = Blueprint('base', __name__)

@base.route('/')
@base.route('/home')
def home():
    return render_template('home.html')

@base.route('/portfolio')
def portfolio():
    return render_template('portfolio.html')

@base.route('/contact')
def contact():
    return render_template('contacto.html')

webpersonal/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daniel - {% block title %} {% endblock %}</title>
</head>
<body>
<header>
    <a href="{{url_for('base.home')}}">Inicio</a>
    <a href="{{url_for('base.portfolio')}}">Portafolio</a>
    <a href="{{url_for('base.contact')}}">Contacto</a>
</header>
{% block content %}
{% endblock %}
<footer>
    Pie de página
</footer>
</body>
</html>

webpersonal/templates/contacto.html
{% extends 'base.html' %}
{% block title %} Contacto {% endblock %}
{% block content %}
    <h1>Página de contacto</h1>
{% endblock %}

webpersonal/templates/home.html
{% extends 'base.html' %}

{% block title %} Inicio {% endblock %}
{% block content %}
<h1>Página de inicio</h1>
{% endblock %}

webpersonal/templates/portfolio.html
{% extends 'base.html' %}
{% block title %} Portafolio {% endblock %}
{% block content %}
<h1>Página de portafolio</h1>
{% endblock %}

webpersonal/templates/project/create.html
{% extends './base.html' %}

{% block title %} Proyectos {% endblock %}

{% block content %}
<h2>Insertar Proyectos</h2>
<form action="{{url_for('project.insert')}}" method="post">
    <label for="title">Titulo</label>
    <input type="text" id="title" name="title">
    <br>
    <label for="description">Descripción</label>
    <br>
    <textarea id="description" name="description" cols="50" rows="10"></textarea>
    <br>
    <input type="submit" value="Guardar">
</form>
{% endblock %}

webpersonal/templates/project/edit.html
{% extends './base.html' %}

{% block title %} Proyectos {% endblock %}

{% block content %}
<h2>Insertar Proyectos</h2>
<form action="{{url_for('project.update', id=project.id)}}" method="post">
    <label for="title">Titulo</label>
    <input type="text" id="title" name="title" value="{{project.title}}">
    <br>
    <label for="description">Descripción</label>
    <br>
    <textarea id="description" name="description" cols="50" rows="10">{{project.description}}</textarea>
    <br>
    <input type="submit" value="Guardar">
</form>
{% endblock %}

webpersonal/templates/project/index.html
{% extends './base.html' %}

{% block title %} Proyectos {% endblock %}

{% block content %}
<br><br>
<a href="{{url_for('project.create')}}">Crear nuevo proyecto</a>
<table>
    <tr>
        <th>Titulo</th>
        <th>Descripción</th>
    </tr>
    {% for project in projects %}
    <tr>
        <td>
            {{project.title}}
        </td>
        <td>
            {{project.description}}
        </td>
        <td>
            <a href="{{url_for('project.edit', id=project['id'])}}">Editar</a>
        </td>
        <td>
            <a href="{{url_for('project.delete', id=project['id'])}}">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}